### ISSUE TITLE
Installation in jupyterlab dev mode

### ISSUE THREAD

**Issue by lzfxxx** [jupyterlab/jupyterlab-monaco#11]
I made some modification on original jupyterlab application, so I need to run the dev mode.
I got such error after running `jlpm run add:sibling ./extensions/jupyterlab-monaco`(I placed the `jupyterlab-monaco` repo under `extensions` folder under jupyterlab code root directory):
```
$ jlpm run add:sibling ./extensions/jupyterlab-monaco
yarn run v1.3.2
$ node buildutils/lib/add-sibling.js ./extensions/jupyterlab-monaco
> jlpm run integrity
$ node buildutils/lib/ensure-repo.js
npm ERR! code E404
npm ERR! 404 Not found : file-loader!..
npm ERR! 404 
npm ERR! 404  'file-loader!..' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain special characters ("~'!()*")
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhaofengli/.npm/_logs/2018-06-20T06_52_57_173Z-debug.log
child_process.js:644
    throw err;
    ^

Error: Command failed: npm view file-loader!.. version
npm ERR! code E404
npm ERR! 404 Not found : file-loader!..
npm ERR! 404 
npm ERR! 404  'file-loader!..' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain special characters ("~'!()*")
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhaofengli/.npm/_logs/2018-06-20T06_52_57_173Z-debug.log

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at Object.getDependency (/Users/zhaofengli/projects/goldersgreen/frontend/src/packages/jupyterlab_package/buildutils/lib/get-dependency.js:69:45)
    at /Users/zhaofengli/projects/goldersgreen/frontend/src/packages/jupyterlab_package/buildutils/lib/ensure-package.js:83:51
    at Array.forEach (<anonymous>)
    at Object.ensurePackage (/Users/zhaofengli/projects/goldersgreen/frontend/src/packages/jupyterlab_package/buildutils/lib/ensure-package.js:74:11)
    at ensureIntegrity (/Users/zhaofengli/projects/goldersgreen/frontend/src/packages/jupyterlab_package/buildutils/lib/ensure-repo.js:194:46)
    at Object.<anonymous> (/Users/zhaofengli/projects/goldersgreen/frontend/src/packages/jupyterlab_package/buildutils/lib/ensure-repo.js:240:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jasongrout** [comment]
What commit are you on? Is this using the source of 0.32.1, or master?

It could be that the `file-loader` trick doesn't work with add:sibling (CC @saulshanabrook). It could also be that the plugin needs to be updated for whatever dev commit you are on.

**Comment by lzfxxx** [comment]
@jasongrout I'm working on 0.31.1, but I've also tried `add:sibling` in master commit which also has the same error. I think 

> the file-loader trick doesn't work with add:sibling 

might be the right explanation for this problem. So what should I do to resolve this problem? Maybe report this to jupyterlab main repo?
